name: "🐞 Bug Report"
description: Report a Bug to Rspack
title: "[Bug]: "
labels: ["C-bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue! Before submitting, please note:

         - Confirm that your problem cannot be solved by official documentation.
         - Make sure you searched in the [Issues](https://github.com/modern-js-dev/rspack/issues) and didn't find the same issue.
         - If it's not bug report, please post on the [Discussions](https://github.com/modern-js-dev/rspack/discussions).

  - type: input
    id: versions
    attributes:
      label: Rspack Version
      description: Run `npm ls @rspack/core` or `pnpm ls @rspack/core --depth Infinity`.
      placeholder: "@rspack/core@1.0.0"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please describe the Bug, it would be better to provide a screenshot.
    validations:
      required: true

  - type: input
    id: reproduce
    attributes:
      label: Reproduce link
      description: "Please provide a simplest reproduction of the problem (minimal demo without redundant dependencies). You can create it on [CodeSandbox](https://codesandbox.io/), or provide the URL of the project:"
      placeholder: paste link here

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Reproduce Steps
      description: Please provide the simplest steps so that we can quickly reproduce the problem.
      placeholder: |
        For example:
        1. execute `yarn dev`
        2. find `xxx` error message in the console
    validations:
      required: true
