name: 我遇到了一个 Bug
description: 进行 Bug 反馈
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        在提交 Bug 报告前，请注意：

        - 确认你的问题无法通过官方文档得到解决。
        - 确认你搜索过历史 [issue](https://github.com/youzan/vant/issues)，并且没有发现同样的问题。
        - 如果不是反馈 Bug，请到 [Discussions 讨论区](https://github.com/youzan/vant/discussions) 发帖。

